#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

o3de_set(PAL_EXECUTABLE_APPLICATION_FLAG)
o3de_set(PAL_LINKOPTION_MODULE MODULE)

o3de_set(O3DE_PAL_TRAIT_BUILD_HOST_GUI_TOOLS FALSE)
o3de_set(O3DE_PAL_TRAIT_BUILD_HOST_TOOLS FALSE)
o3de_set(O3DE_PAL_TRAIT_BUILD_SERVER_SUPPORTED FALSE)
o3de_set(O3DE_PAL_TRAIT_BUILD_UNIFIED_SUPPORTED FALSE)
o3de_set(O3DE_PAL_TRAIT_BUILD_UNITY_SUPPORTED TRUE)
o3de_set(O3DE_PAL_TRAIT_BUILD_UNITY_EXCLUDE_EXTENSIONS)
o3de_set(O3DE_PAL_TRAIT_BUILD_EXCLUDE_ALL_TEST_RUNS_FROM_IDE FALSE)
o3de_set(O3DE_PAL_TRAIT_BUILD_CPACK_SUPPORTED FALSE)

o3de_set(O3DE_PAL_TRAIT_PROF_PIX_SUPPORTED FALSE)

# Test library support
o3de_set(O3DE_PAL_TRAIT_TEST_GOOGLE_TEST_SUPPORTED FALSE)
o3de_set(O3DE_PAL_TRAIT_TEST_GOOGLE_BENCHMARK_SUPPORTED FALSE)
o3de_set(O3DE_PAL_TRAIT_TEST_LYTESTTOOLS_SUPPORTED FALSE)
o3de_set(O3DE_PAL_TRAIT_TEST_PYTEST_SUPPORTED FALSE)
o3de_set(O3DE_PAL_TRAIT_TEST_TARGET_TYPE MODULE)

if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    o3de_set(O3DE_PAL_TRAIT_COMPILER_ID Clang)
    o3de_set(O3DE_PAL_TRAIT_COMPILER_ID_LOWERCASE clang)
else()
    message(FATAL_ERROR "Compiler ${CMAKE_CXX_COMPILER_ID} not supported in ${O3DE_PAL_PLATFORM_NAME}")
endif()
